FROM openjdk:17-jdk-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

COPY target/backend-test-0.0.1-SNAPSHOT.jar test-backend-app.jar

ENTRYPOINT ["java", "-jar", "test-backend-app.jar"]